version: "3.9"
services:

  backend:
    image: backend
    container_name: backend
    build: 
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    restart: on-failure
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - default
  #   depends_on:
  #     - database

  frontend:
    image: frontend
    container_name: frontend
    build: 
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    restart: on-failure
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - default

  # database:
  #   image: postgres
  #   container_name: database
  #   restart: on-failure
  #   tty: true
  #   stdin_open: true
  #   environment:
  #   env_file:
  #     - ./docker/database/.env
  # #   # volumes:
  # #     # - database:/var/lib/mysql
  # #   # ports:
  # #     # - "3306:3306"
  #   networks:
  #     - default

# volumes:
#   website:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/website/
#       o: bind

#   database:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/database/
#       o: bind

networks:
  default:
    name: transcendence_network
    driver: bridge
