version: "3.9"
services:

  backend:
    image: node
    container_name: backend
    restart: on-failure
    tty: true
    stdin_open: true
    # volumes:
    #   - website:/var/www/
    # ports:
      # - "443:443"
    networks:
      - default

  # frontend:
  #   image: npm
  #   container_name: frontend
  #   restart: on-failure
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - website:/var/www/
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - default
  #   depends_on:
  #     - postgres

  database:
    image: postgres
    container_name: database
    restart: always
    tty: true
    stdin_open: true
    # volumes:
      # - database:/var/lib/mysql
    # ports:
      # - "3306:3306"
    networks:
      - default

# volumes:
#   website:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/website/
#       o: bind

#   database:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/database/
#       o: bind

networks:
  default:
    name: transcendence_network
    driver: bridge
