name: linter
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: install node v12
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 12
    
    - name: yarn install
      run: yarn install

    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: apps # only if a different glob is needed, default: src
